### ISSUE TITLE
Planned arrival and departure should be optional

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-omobilities#23]
Our IRO reports that the currently defined `<planned-arrival-date>` and `<planned-departure-date>` cannot be supplied for nominations, so they should not be required (as they currently are).

Therefore, unless someone votes against it, I will make them optional. @erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
> Are you going to change planned_arrival_after parameter of index method or introduce a new one to allow client asking only for current mobilities?

I forgot about this parameter. Great question. My guess is that mobilities without planned arrival date should always be returned, regardless of the value of `planned_arrival_after` parameter.

> Will be the academic year parameter (issue #24) required? It would be hard to identify mobilities without any required temporal property.

Yes, I think academic year should be required. We could also consider replacing `planned_arrival_after` parameter with some other parameter which would match the academic year(s).

**Comment by wrygiel** [comment]
> We could also consider replacing `planned_arrival_after` parameter with some other parameter which would match the academic year(s).

Can anyone see arguments against doing that?

**Comment by wrygiel** [comment]
TODO: We also need to specify how `planned_arrival_after` parameters should work after this change. Related thread: https://github.com/erasmus-without-paper/ewp-specs-mobility-flowcharts/issues/3#issuecomment-327441816

**Comment by NicoVanMoortel** [comment]
We prefer to have "planned-arrival/departure-date" required but we can work around it if this proves to be a problem for some partners.

We agree that an academic year parameter will be necessary and wonder if it would be beneficial to add an academic term.

**Comment by wrygiel** [comment]
> We agree that an academic year parameter will be necessary and wonder if it would be beneficial to add an academic term.

Thus far, academic terms [don't](https://github.com/erasmus-without-paper/general-issues/issues/7) have universal IDs. Only academic years [do](https://github.com/erasmus-without-paper/ewp-specs-architecture/issues/14).

**Comment by wrygiel** [comment]
Warsaw says that `<planned-arrival-date>` and `<planned-departure-date>` cannot be supplied for nominations. However, nominations are usually done in context of a certain academic year, or even an academic term, so perhaps we can supply at least *some* data here?

The reason I'm asking this is that I believe we always should be able to group mobilities *at least* by their academic year. I don't think that sending a nomination and not saying which year it this nomination is about, is valid. Is it?

* Would it be possible for Warsaw to supply some kind of `<planned-arrival-academic-year-id>` for nominations?

* If so, then do we need two of such year IDs, or a single one would suffice? Is it possible for a single nomination to span two academic years? (I seem to remember we have already discussed that, but I cannot recall the result of this discussion, sorry.)

@janinamincer-daszkiewicz @mkurzydlowski @MartaJuzepczuk @kamil-olszewski-uw

**Comment by kamil-olszewski-uw** [comment]
All nominations/mobilities are always defined in context of particular academic year. Therefore, it's possible to use arrival academic year as parameter. I think word "planned" in proposed parameter name is unnecessary and it suggests that academic year of mobility may change, which is not possible.

I think Erasmus+ rules allow for mobilities only in context of **one** academic year. We don't have longer (Erasmus or non-Erasmus) mobilities at University of Warsaw.

**Comment by wrygiel** [comment]
> I think Erasmus+ rules allow for mobilities only in context of one academic year.

In this case, the word "arrival" also seems unnecessary in this element/parameter. We could simply name it "the academic year of this mobility", I think.
