### ISSUE TITLE
Attaching and approving LA PDFs

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-omobilities#26]
Polish developers suggested (though, as usual, in private conversations), that these PDFs (either scanned or generated) would be useful for them. If I understood it correctly, for archiving.

They also suggested, that perhaps we might allow receiving HEIs to approve LAs based on such PDFs (instead of approving XML contents).

Related question:

If we allow approving PDF LAs, then should we make it optional to support `<components-studied>` and `<components-recognized>` elements? If we did, then HEIs would be able to choose which way of LA approval they support - either the electronic way, or the PDF way, or both.

**Comment by EvelienRenders** [comment]
Is this questions still 'open'/relevant? I now see it's from 2017 ;)

**Comment by janinamincer-daszkiewicz** [comment]
Yes, and it will soon become more ergent when we start connecting OLA to EWP.

**Comment by EvelienRenders** [comment]
My first instinct is that we should not want the institutions to have the option to approve LA's in PDF-form. Because that would mean that they can circumvent putting the data in the system, and thus the data cannot be sent via EWP ... right? Or perhaps I do not understand the question in full @wrygiel 

If they only need the PDF's for archiving, then they can mailmerge the data into PDF's whenever they please right? Just as you can already download a PDF of the OLA from the Dashboard.

**Comment by janinamincer-daszkiewicz** [comment]
@georgschermann could you comment? You represent many clients.

**Comment by georgschermann** [comment]
Sorry for the late answer.
Currently we have a lot of University working solely with scanned PDFs, with and without signatures.
We will have some Universities serving the Courses and LAs from different hosts, which could cause problems / additional effort for the host serving the LA data.
I feel if we allow PDF-only LAs, more of our Universities would use it, but most would probably use the PDF-only way.

The main question is: what will be mandatory in the Erasmus program? LA Data or will PDFs be enough?

If PDF is enough for the EC I would argue that PDF-only LAs should be allowed, they would significantly lower the entrance barrier for most Universities.

**Comment by kamil-olszewski-uw** [comment]
It has been collectively agreed (and accepted by Daiga) that there will be no (even optional) PDF exchange. Any initial mention of PDFs has been removed from the API.
