### ISSUE TITLE
New value of MobilityStatus type

### ISSUE THREAD

**Issue by kamil-olszewski-uw** [erasmus-without-paper/ewp-specs-api-omobilities#28]
MobilityStatus type consists of 5 values: nomination, live, rejected, recognized (finished), cancelled.

Nomination:
> The sending HEI has nominated the student for mobility. The proposal has not yet been accepted nor rejected by the receiving HEI.

Live:
> The nomination has been accepted by the receiving HEI. This status doesn't usually change throughout the mobility.

From the Outgoing Mobilities Update endpoint update request:
>name="update-statuses-v1" - This request is usually sent by the receiving HEI when it wants to accept or reject a group of nominations proposed by the sending HEI. In other words, it allows to suggest that the status of the mobility should be changed from "nomination" to either "live" or "rejected".

IRO of University of Warsaw says that another mobility status is needed, because "live" means that all formalities have been settled, Learning Agreement is signed etc. The name of the new status could be **nomination-verified**: the nomination was recognized by the receiving university as formally correct and complying with cooperation conditions; now is the time for settling formalities, sending student's documents, creating Learning Agreement Before the Mobility and so on.

This addition would affect get endpoint response and update endpoint request.

@erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
So, the conceptual graph of state transitions would look something like this...

![image](https://user-images.githubusercontent.com/2168535/32948296-09f6f416-cb9f-11e7-8b68-28a0f22f7cb9.png)

**Comment by wrygiel** [comment]
@erasmus-without-paper/all-members please comment. Does anyone see something against adding this new mobility status?

**Comment by wrygiel** [comment]
Since there were no comments here, I will include this new type in the upcoming version.
