### ISSUE TITLE
Changes of fields and types for the EWP - Dashboard integration

### ISSUE THREAD

**Issue by MartaJuzepczuk** [erasmus-without-paper/ewp-specs-api-omobilities#34]
In this issue we will discuss changes in the Outgoing Mobilities API and in the Dashboard which are required to make the Dashboard an EWP Outgoing Mobilities API's server and client.

**Comment by MartaJuzepczuk** [comment]
1. In all EWP APIs institutions are identified by the SCHAC codes. It seems that the Dashboard should also keep and use them.
2. Are the coordinators names in the dashboard database kept as one string? Maybe it would be better to send the first name and the last name as two separate fields?
3. What is the Student ID (optional in Dashboard, not present in EWP). Do we want to exchange it in the Learning Agreements API and Outgoing Mobilities API?
4. Do we want to exchange student telephone numbers in the Learning Agreements API (currently optional in EWP and in the Dashboard)?

**Comment by kamil-olszewski-uw** [comment]
Ad 4. Student telephone numbers will not be included in the new version of LA.

**Comment by kamil-olszewski-uw** [comment]
Ad 3. The European Student Identifier is already added to the APIs, so the question is no longer relevant.
